arb-dir: assets/l10n
template-arb-file: string_en.arb
output-dir: lib/l10n
output-localization-file: translations.dart
output-class: Translations
preferred-supported-locales: ["en"]
synthetic-package: false
nullable-getter: false